# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "91aabbe26f00a872aade0c940ee127c4"
application_url = "https://assumed-week-warned-doc.trycloudflare.com"
embedded = true
name = "Dynamic Store Locator"
handle = "dynamic-store-locator"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://assumed-week-warned-doc.trycloudflare.com/auth/callback",
  "https://assumed-week-warned-doc.trycloudflare.com/auth/shopify/callback",
  "https://assumed-week-warned-doc.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "dynamic-store-locator.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
